<?php

namespace Database\Seeders;
use App\Models\{Product,Shipment,User};
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
class DatabaseSeeder extends Seeder {
 public function run(): void {
  User::create(['name'=>'NexPort Administrator','email'=>'admin@nexport.test','password'=>Hash::make('password')]);
  $items=[
   ['Toyota Land Cruiser Prado TXL','toyota-land-cruiser-prado-txl','Vehicles','Toyota','Japan',42000,'Used','https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=85','VEH-2045',2024,['Mileage'=>'15,000 KM','Engine'=>'2.8L Diesel','Transmission'=>'Automatic','Drive'=>'4WD']],
   ['Mercedes-Benz Actros 2645','mercedes-benz-actros-2645','Vehicles','Mercedes-Benz','Germany',68500,'Used','https://images.unsplash.com/photo-1586191582151-f73872dfd183?auto=format&fit=crop&w=1200&q=85','VEH-2088',2022,['Engine'=>'12.8L Diesel','Transmission'=>'Automatic','Body'=>'Prime mover']],
   ['Honda Africa Twin Adventure','honda-africa-twin-adventure','Motorcycles','Honda','Japan',15900,'New','https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=1200&q=85','MOTO-1031',2025,['Engine'=>'1084cc','Transmission'=>'6-speed','ABS'=>'Dual channel']],
   ['CAT 320 Hydraulic Excavator','cat-320-hydraulic-excavator','Machinery','Caterpillar','USA',118000,'Used','https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1200&q=85','MAC-4402',2021,['Operating weight'=>'22,100 kg','Power'=>'121 kW','Hours'=>'3,480']],
   ['Prime Grade Reinforcement Steel','prime-grade-reinforcement-steel','Construction Materials','Baosteel','China',740,'New','https://images.unsplash.com/photo-1518709414768-a88981a4515d?auto=format&fit=crop&w=1200&q=85','CON-3024',null,['Grade'=>'B500B','Size'=>'8–32 mm','Unit'=>'Per metric tonne']],
   ['Perkins 100kVA Diesel Generator','perkins-100kva-diesel-generator','Machinery','Perkins','United Kingdom',14350,'New','https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1200&q=85','MAC-4419',2025,['Output'=>'100 kVA','Phase'=>'3 phase','Frequency'=>'50 Hz']],
   ['Industrial Solar Power Kit 20kW','industrial-solar-power-kit-20kw','Electronics','SunPower','China',18200,'New','https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=1200&q=85','ELE-5501',2025,['Capacity'=>'20 kW','Panels'=>'36 × 550W','Warranty'=>'15 years']],
   ['Genuine Toyota Hilux Service Kit','toyota-hilux-service-kit','Spare Parts','Toyota','UAE',295,'New','https://images.unsplash.com/photo-1487754180451-c456f719a1fc?auto=format&fit=crop&w=1200&q=85','SP-7712',null,['Compatibility'=>'Hilux 2016–2025','Parts'=>'12 piece kit','Type'=>'Genuine OEM']],
  ];
  foreach($items as $i){$p=Product::create(['name'=>$i[0],'slug'=>$i[1],'category'=>$i[2],'brand'=>$i[3],'model'=>$i[0],'origin'=>$i[4],'current_location'=>$i[4],'price'=>$i[5],'fob_price'=>$i[5],'currency'=>'USD','condition'=>$i[6],'availability'=>'In Stock','image'=>$i[7],'stock_no'=>$i[8],'year'=>$i[9],'specifications'=>$i[10],'description'=>'Professionally sourced through our verified international supplier network. Every unit is inspected and documented before shipping, with complete logistics support to your destination. Contact our international trade team for inspection reports, shipping schedules and destination-specific landed cost estimates.','featured'=>true,'purchase_mode'=>'quote','delivery_time'=>'4–8 weeks','shipping_information'=>'Shipping schedules and final landed costs are confirmed after destination and cargo details are verified.','seo_title'=>$i[0].' for Export | NexPort Global','seo_description'=>'View specifications, pricing and international shipping options for '.$i[0].'.']);foreach([$i[7],$i[7].'&sat=-15',$i[7].'&contrast=12'] as $order=>$url)$p->images()->create(['path'=>$url,'alt_text'=>$i[0],'sort_order'=>$order]);}
  Shipment::create(['tracking_number'=>'NPG-78245190','order_number'=>'ORD-2026-0184','product'=>'Toyota Land Cruiser Prado TXL','origin'=>'Yokohama, Japan','destination'=>'Dar es Salaam, Tanzania','current_status'=>'In Transit','events'=>[['status'=>'Order Confirmed','date'=>'2026-08-10','description'=>'Order and payment verified'],['status'=>'Inspection Completed','date'=>'2026-08-15','description'=>'Independent inspection passed'],['status'=>'Loaded at Port','date'=>'2026-08-22','description'=>'Loaded aboard MV Horizon'],['status'=>'In Transit','date'=>'2026-08-24','description'=>'Vessel departed Yokohama'],['status'=>'Arrived at Destination Port','date'=>null,'description'=>'Estimated 18 September 2026'],['status'=>'Customs Clearance','date'=>null,'description'=>'Pending'],['status'=>'Ready for Collection','date'=>null,'description'=>'Pending']]]);
 }
}
