<?php
namespace App\Http\Controllers;
use App\Models\{Product,ProductImage};
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
class AdminProductController extends Controller {
 public function index(){return view('admin.products.index',['products'=>Product::withCount('images')->latest()->paginate(15)]);}
 public function create(){return view('admin.products.form',['product'=>new Product,'specifications'=>[]]);}
 public function store(Request $r){$p=Product::create($this->validated($r));$this->syncImages($r,$p);return redirect()->route('admin.products.index')->with('success','Product created and published successfully.');}
 public function edit(Product $product){$product->load('images');return view('admin.products.form',['product'=>$product,'specifications'=>$product->specifications??[]]);}
 public function update(Request $r,Product $product){$product->update($this->validated($r,$product));$this->syncImages($r,$product);return redirect()->route('admin.products.index')->with('success','Product updated successfully.');}
 public function destroy(Product $product){foreach($product->images as $i)$this->deleteFile($i->path);$product->delete();return back()->with('success','Product removed.');}
 public function destroyImage(ProductImage $image){$this->deleteFile($image->path);$image->delete();return back()->with('success','Image removed.');}
 private function validated(Request $r,?Product $p=null):array{$d=$r->validate(['name'=>'required|string|max:180','slug'=>'nullable|string|max:190|unique:products,slug,'.($p?->id??'NULL'),'category'=>'required|string|max:100','subcategory'=>'nullable|string|max:100','brand'=>'nullable|string|max:100','model'=>'nullable|string|max:100','description'=>'required|string','price'=>'nullable|numeric|min:0','fob_price'=>'nullable|numeric|min:0','cif_price'=>'nullable|numeric|min:0','shipping_cost'=>'nullable|numeric|min:0','currency'=>'required|in:USD,EUR,GBP,TZS,CNY,AED','origin'=>'required|string|max:100','current_location'=>'nullable|string|max:150','stock_no'=>'required|string|max:80|unique:products,stock_no,'.($p?->id??'NULL'),'year'=>'nullable|integer|min:1900|max:'.(date('Y')+2),'condition'=>'required|in:New,Used','availability'=>'required|string|max:80','purchase_mode'=>'required|in:quote,buy,both','shipping_destination'=>'nullable|string|max:150','delivery_time'=>'nullable|string|max:120','shipping_information'=>'nullable|string','seo_title'=>'nullable|string|max:180','seo_description'=>'nullable|string|max:500','featured'=>'nullable|boolean','image_url'=>'nullable|url|max:1000','images.*'=>'nullable|image|mimes:jpg,jpeg,png,webp|max:5120','image_urls'=>'nullable|string','spec_keys.*'=>'nullable|string|max:100','spec_values.*'=>'nullable|string|max:500']);$d['slug']=Str::slug($d['slug']?:$d['name']);$d['featured']=$r->boolean('featured');$spec=[];foreach($r->input('spec_keys',[]) as $i=>$key)if(trim($key)!=='')$spec[trim($key)]=trim($r->input('spec_values.'.$i,''));$d['specifications']=$spec;$d['image']=$d['image_url']??$p?->image??'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?auto=format&fit=crop&w=1200&q=85';unset($d['image_url'],$d['images'],$d['image_urls'],$d['spec_keys'],$d['spec_values']);return $d;}
 private function syncImages(Request $r,Product $p):void{foreach($r->input('image_order',[]) as $id=>$order)ProductImage::where('product_id',$p->id)->whereKey($id)->update(['sort_order'=>(int)$order]);$next=(int)$p->images()->max('sort_order')+1;if($r->filled('image_url')&&!$p->images()->where('path',$r->image_url)->exists())$p->images()->create(['path'=>$r->image_url,'alt_text'=>$p->name,'sort_order'=>$next++]);foreach(preg_split('/\r\n|\r|\n/',trim((string)$r->image_urls)) as $url)if(filter_var(trim($url),FILTER_VALIDATE_URL))$p->images()->create(['path'=>trim($url),'alt_text'=>$p->name,'sort_order'=>$next++]);foreach($r->file('images',[]) as $file)$p->images()->create(['path'=>Storage::url($file->store('products','public')),'alt_text'=>$p->name,'sort_order'=>$next++]);}
 private function deleteFile(string $path):void{if(str_starts_with($path,'/storage/'))Storage::disk('public')->delete(Str::after($path,'/storage/'));}
}
